defaults: &cfdefaults
  docker:
    - image: governmentpaas/cf-cli
  steps:
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /tmp/workspace
    - run: cf -v
    - run: cf login -a api.run.pivotal.io -o FrameworksAndRuntimes -s rbaxter -u $CF_USER_NAME -p $CF_PASSWORD

version: 2.0

jobs:
  "blueorgreenservice":
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/blueorgreenservice
    steps:
      - checkout
      - run: cd blueorgreenservice && ./mvnw clean package
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: blueorgreenservice
          # Must be relative path from root
          paths:
            - target/blueorgreen-0.0.1-SNAPSHOT.jar
            - manifest.yml

  "blueorgreenfrontend":
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/blueorgreenfrontend
    steps:
      - checkout
      - run: cd blueorgreenfrontend && ./mvnw clean package
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: blueorgreenfrontend
          # Must be relative path from root
          paths:
            - target/blueorgreenfrontend-0.0.1-SNAPSHOT.jar
            - manifest.yml

  "blueorgreenservicedeploy":
    <<: *cfdefaults
    steps:
      - run: cd /tmp/workspace && cf push blueservice

  "blueorgreenfrontenddeploy":
      <<: *cfdefaults
      steps:
        - run: cd /tmp/workspace && cf push

workflows:
  version: 2
  build:
    jobs:
      - "blueorgreenservice"
      - "blueorgreenfrontend"
      - "blueorgreenservicedeploy":
          requires:
            - "blueorgreenservice"
      - "blueorgreenfrontenddeploy":
          requires:
            - "blueorgreenfrontend"
